### ISSUE TITLE
您好，请教集群问题

### ISSUE THREAD

**Issue by bergkamp2008999** [Howinfun/winfun-pulsar-spring-boot-starter#1]
您好，请问如果是pulsar集群，初始化的代码是这样写吗？pulsar://pulsar01:6650,pulsar02:6650,pulsar03:6650，如果这样写，假如pulsar01出问题了，那么程序如何处理呢？会尝试连接pulsar01直到他启动为止吗？

**Comment by Howinfun** [comment]
是的，是这么写；至于程序如何处理，看Pulsar的源码即可，这个starter只是基于Pulsar 的API做了一层封装～

**Comment by bergkamp2008999** [comment]
哦，我运行结果是，他每隔多长时间会重连，源码应该看那个pulsar client.jar吧

**Comment by Howinfun** [comment]
是的是的

**Comment by bergkamp2008999** [comment]
谢谢哥们^_^

**Comment by Howinfun** [comment]
客气啥 哈哈
